@extends('layouts.admin')
@section('title', $order->code.' — Printlab')
@section('heading', 'Detail transaksi')
@section('content')
<div class="mx-auto max-w-5xl"><a href="{{ route('admin.orders.index') }}" class="text-xs font-semibold text-[#77786f]">← Kembali ke transaksi</a><div class="mt-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p class="text-[10px] font-bold uppercase tracking-[.2em] text-[#879f32]">{{ $order->created_at->format('d F Y · H:i') }}</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">{{ $order->code }}</h1></div><span class="w-fit rounded-full bg-[#f0efe9] px-4 py-2 text-xs font-bold">{{ ['pending_payment' => 'Menunggu pembayaran', 'paid' => 'Dibayar', 'processing' => 'Diproses', 'ready' => 'Siap dikirim/diambil', 'completed' => 'Selesai', 'cancelled' => 'Dibatalkan'][$order->status] }}</span></div>
<div class="mt-7 grid gap-5 lg:grid-cols-[1fr_340px]">
    <div class="space-y-5">
        <section class="rounded-2xl border border-black/5 bg-white p-5"><h2 class="text-sm font-bold">Item pesanan</h2>@foreach ($order->items as $item)<div class="mt-4 flex justify-between gap-4 border-t border-black/5 pt-4"><div><p class="text-sm font-semibold">{{ $item->product_name }}</p><p class="mt-1 text-xs text-[#77786f]">{{ $item->color_name }} · {{ $item->quantity }} pcs · {{ $item->fulfillment_type === 'ready' ? 'Ready' : 'PO '.$item->lead_days.' hari' }}</p>@if ($item->customization)<div class="mt-3 rounded-xl bg-[#f7f6f2] p-3"><p class="text-xs font-bold">Nama emboss: “{{ $item->customization['name'] }}” <span class="font-normal text-[#77786f]">({{ $item->customization['name_length'] }} karakter)</span></p><div class="mt-2 flex flex-wrap gap-2">@foreach (['base' => 'Base', 'button' => 'Tombol', 'name' => 'Tulisan'] as $component => $label)<span class="inline-flex items-center gap-1.5 rounded-full bg-white px-2 py-1 text-[10px]"><i class="size-2.5 rounded-full" style="background-color: {{ $item->customization['components'][$component]['hex_code'] }}"></i>{{ $label }}: {{ $item->customization['components'][$component]['color_name'] }}</span>@endforeach</div></div>@endif</div><p class="text-sm font-bold">Rp {{ number_format($item->subtotal, 0, ',', '.') }}</p></div>@endforeach<div class="mt-4 flex justify-between border-t border-black/10 pt-4 text-sm"><span>Total</span><strong>Rp {{ number_format($order->subtotal, 0, ',', '.') }}</strong></div></section>
        <section class="rounded-2xl border border-black/5 bg-white p-5"><h2 class="text-sm font-bold">Pelanggan & pengiriman</h2><p class="mt-4 text-sm font-semibold">{{ $order->customer_name }}</p><p class="mt-1 text-xs text-[#77786f]">{{ $order->customer_phone }}</p><p class="mt-3 whitespace-pre-line text-sm leading-6 text-[#5f6058]">{{ $order->shipping_address }}</p><a target="_blank" rel="noreferrer" href="https://wa.me/{{ $order->customer_phone }}" class="mt-4 inline-flex rounded-full bg-[#e8f3cf] px-4 py-2 text-xs font-bold text-[#53632c]">Hubungi via WhatsApp ↗</a></section>
        <section class="rounded-2xl border border-black/5 bg-white p-5"><h2 class="text-sm font-bold">Riwayat status</h2><div class="mt-4 space-y-4">@foreach ($order->statusHistories->sortByDesc('created_at') as $history)<div class="flex gap-3 text-xs"><span class="mt-1 size-2 shrink-0 rounded-full bg-[#9bbd44]"></span><div><p class="font-semibold">{{ $history->to_status }} <span class="font-normal text-[#77786f]">· {{ $history->user?->name ?? 'Sistem' }}</span></p><p class="mt-1 text-[#85867d]">{{ $history->created_at->format('d M Y, H:i') }}</p></div></div>@endforeach</div></section>
    </div>
    <aside class="h-fit rounded-2xl border border-black/5 bg-white p-5"><h2 class="text-sm font-bold">Perbarui pesanan</h2><form method="POST" action="{{ route('admin.orders.update', $order) }}" class="mt-5 space-y-4">@csrf @method('PATCH')<div><label class="mb-2 block text-xs font-bold">Status pesanan</label><select name="status" class="form-input">@foreach (['pending_payment' => 'Menunggu pembayaran', 'paid' => 'Dibayar', 'processing' => 'Diproses', 'ready' => 'Siap dikirim/diambil', 'completed' => 'Selesai', 'cancelled' => 'Dibatalkan'] as $value => $label)<option value="{{ $value }}" @selected($order->status === $value)>{{ $label }}</option>@endforeach</select></div><div><label class="mb-2 block text-xs font-bold">Status pembayaran</label><select name="payment_status" class="form-input"><option value="unpaid" @selected($order->payment_status === 'unpaid')>Belum dibayar</option><option value="confirmed" @selected($order->payment_status === 'confirmed')>Dikonfirmasi</option></select></div><p class="rounded-xl bg-[#f5f4ef] p-3 text-[10px] leading-4 text-[#77786f]">Membatalkan pesanan akan mengembalikan stok ready satu kali. Pesanan batal tidak dapat diaktifkan kembali.</p><button class="w-full rounded-full bg-[#20211f] px-5 py-3 text-xs font-bold text-white">Simpan status</button></form></aside>
</div></div>
@endsection
