@extends('layouts.admin')
@section('title', ($product->exists ? 'Edit produk' : 'Tambah model').' — Printlab')
@section('heading', 'Katalog & stok')
@section('content')
<div class="mx-auto max-w-4xl"><a href="{{ route('admin.products.index') }}" class="text-xs font-semibold text-[#77786f]">← Kembali ke produk</a><div class="mt-3 flex items-end justify-between gap-3"><div><p class="text-[10px] font-bold uppercase tracking-[.2em] text-[#879f32]">{{ $product->exists ? 'Perbarui katalog' : 'Katalog baru' }}</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">{{ $product->exists ? $product->name : 'Tambah model' }}</h1></div></div>
<form method="POST" action="{{ $product->exists ? route('admin.products.update', $product) : route('admin.products.store') }}" enctype="multipart/form-data" class="mt-7 space-y-7 rounded-[1.8rem] border border-black/5 bg-white p-5 sm:p-8">
    @csrf @if ($product->exists) @method('PUT') @endif
    <section class="grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label class="mb-2 block text-xs font-bold">Nama model</label><input class="form-input" name="name" value="{{ old('name', $product->name) }}" required maxlength="160" placeholder="Contoh: Mini planter"></div><div class="sm:col-span-2"><label class="mb-2 block text-xs font-bold">Deskripsi</label><textarea class="form-input" name="description" rows="3">{{ old('description', $product->description) }}</textarea></div><div><label class="mb-2 block text-xs font-bold">Harga (Rp)</label><input class="form-input" type="number" name="price" min="1000" value="{{ old('price', $product->price) }}" required></div><div class="flex items-center gap-3 pt-6"><input type="hidden" name="is_active" value="0"><input class="size-4 accent-[#879f32]" id="is_active" type="checkbox" name="is_active" value="1" {{ old('is_active', $product->exists ? $product->is_active : true) ? 'checked' : '' }}><label for="is_active" class="text-sm font-semibold">Tampilkan di katalog</label></div></section>
    <section class="grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-xs font-bold">Foto produk (JPG, PNG, WEBP · maks 5 MB)</label><input class="form-input file:mr-3 file:rounded-full file:border-0 file:bg-[#eeede7] file:px-3 file:py-1.5 file:text-xs" type="file" name="image" accept="image/jpeg,image/png,image/webp">@if ($product->image_path)<p class="mt-2 text-[10px] text-[#77786f]">Foto sudah tersedia.</p>@endif</div><div><label class="mb-2 block text-xs font-bold">Model 3D (STL atau 3MF · maks 50 MB)</label><input class="form-input file:mr-3 file:rounded-full file:border-0 file:bg-[#eeede7] file:px-3 file:py-1.5 file:text-xs" type="file" name="model_file" accept=".stl,.3mf,model/stl,model/3mf">@if ($product->model_format)<p class="mt-2 text-[10px] text-[#77786f]">Model {{ strtoupper($product->model_format) }} sudah diunggah.</p>@endif</div></section>
    <section><div class="flex items-end justify-between gap-3"><div><h2 class="text-base font-bold">Varian warna</h2><p class="mt-1 text-xs text-[#77786f]">Atur stok warna ready atau estimasi hari untuk PO.</p></div></div><div class="mt-4 space-y-3">
        @forelse ($colors as $color)
            @php($variant = $product->variants->firstWhere('color_id', $color->id))
            <div class="grid gap-3 rounded-2xl bg-[#f6f5f0] p-4 sm:grid-cols-[1.2fr_1fr_1fr_1fr] sm:items-center"><div class="flex items-center gap-2"><span class="size-5 rounded-full border border-black/10" style="background-color: {{ $color->hex_code }}"></span><span class="text-sm font-semibold">{{ $color->name }}</span></div><input type="hidden" name="variants[{{ $color->id }}][color_id]" value="{{ $color->id }}"><div><label class="mb-1 block text-[9px] font-bold uppercase text-[#77786f]">Tipe</label><select name="variants[{{ $color->id }}][availability]" class="form-input !py-2 text-xs"><option value="ready" @selected(old('variants.'.$color->id.'.availability', $variant?->availability) === 'ready')>Ready</option><option value="po" @selected(old('variants.'.$color->id.'.availability', $variant?->availability ?? 'po') === 'po')>Pre-order</option></select></div><div><label class="mb-1 block text-[9px] font-bold uppercase text-[#77786f]">Stok ready</label><input type="number" min="0" name="variants[{{ $color->id }}][stock]" value="{{ old('variants.'.$color->id.'.stock', $variant?->stock ?? 0) }}" class="form-input !py-2 text-xs"></div><div><label class="mb-1 block text-[9px] font-bold uppercase text-[#77786f]">PO (hari)</label><input type="number" min="1" max="365" name="variants[{{ $color->id }}][lead_days]" value="{{ old('variants.'.$color->id.'.lead_days', $variant?->lead_days ?? 14) }}" class="form-input !py-2 text-xs"></div></div>
        @empty
            <p class="rounded-xl bg-[#f6f5f0] p-4 text-sm text-[#77786f]">Tambahkan warna terlebih dahulu dari halaman Produk & stok.</p>
        @endforelse
    </div></section>
    @if ($errors->any())<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700">@foreach ($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <div class="flex flex-col-reverse justify-end gap-3 border-t border-black/5 pt-5 sm:flex-row"><a href="{{ route('admin.products.index') }}" class="rounded-full border border-black/10 px-6 py-3 text-center text-xs font-bold">Batal</a><button class="rounded-full bg-[#20211f] px-7 py-3 text-xs font-bold text-white">{{ $product->exists ? 'Simpan perubahan' : 'Simpan model' }} ↗</button></div>
</form></div>
@endsection
